// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod data {
        pub mod validator {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod unit_validator {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_bar_cabi<T: Guest>(arg0: f32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::validate_bar(arg0);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_psi_cabi<T: Guest>(arg0: f32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::validate_psi(arg0);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    fn validate_bar(val: f32) -> bool;
                    fn validate_psi(val: f32) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_data_validator_unit_validator_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "data:validator/unit-validator#validate-bar")] unsafe extern "C"
                        fn export_validate_bar(arg0 : f32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_validate_bar_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "data:validator/unit-validator#validate-psi")] unsafe extern "C"
                        fn export_validate_psi(arg0 : f32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_validate_psi_cabi::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_data_validator_unit_validator_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_validator_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::data::validator::unit_validator::__export_data_validator_unit_validator_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::data::validator::unit_validator);
    };
}
#[doc(inline)]
pub(crate) use __export_validator_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:data:validator:validator:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 243] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07t\x01A\x02\x01A\x02\x01\
B\x03\x01@\x01\x03valv\0\x7f\x04\0\x0cvalidate-bar\x01\0\x04\0\x0cvalidate-psi\x01\
\0\x04\0\x1ddata:validator/unit-validator\x05\0\x04\0\x18data:validator/validato\
r\x04\0\x0b\x0f\x01\0\x09validator\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
