// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod data {
    pub mod transformer {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod message_transformers {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn convert_to_psi(bar_pressure: f32) -> f32 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "data:transformer/message-transformers")]
                    unsafe extern "C" {
                        #[link_name = "convert-to-psi"]
                        fn wit_import0(_: f32) -> f32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: f32) -> f32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_f32(&bar_pressure)) };
                    ret
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn convert_to_bar(psi_pressure: f32) -> f32 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "data:transformer/message-transformers")]
                    unsafe extern "C" {
                        #[link_name = "convert-to-bar"]
                        fn wit_import0(_: f32) -> f32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: f32) -> f32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_f32(&psi_pressure)) };
                    ret
                }
            }
        }
    }
    pub mod validator {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod unit_validator {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn validate_bar(val: f32) -> bool {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "data:validator/unit-validator")]
                    unsafe extern "C" {
                        #[link_name = "validate-bar"]
                        fn wit_import0(_: f32) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: f32) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_f32(&val)) };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn validate_psi(val: f32) -> bool {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "data:validator/unit-validator")]
                    unsafe extern "C" {
                        #[link_name = "validate-psi"]
                        fn wit_import0(_: f32) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: f32) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_f32(&val)) };
                    _rt::bool_lift(ret as u8)
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod data {
        pub mod transformer {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_runner {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> f32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::run(_rt::string_lift(bytes0));
                    _rt::as_f32(result1)
                }
                pub trait Guest {
                    fn run(source: _rt::String) -> f32;
                }
                #[doc(hidden)]
                macro_rules! __export_data_transformer_component_runner_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "data:transformer/component-runner#run")] unsafe extern "C" fn
                        export_run(arg0 : * mut u8, arg1 : usize,) -> f32 { unsafe {
                        $($path_to_types)*:: _export_run_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_data_transformer_component_runner_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_transformer_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::data::transformer::component_runner::__export_data_transformer_component_runner_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::data::transformer::component_runner);
    };
}
#[doc(inline)]
pub(crate) use __export_transformer_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:data:transformer:transformer:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 433] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xaf\x02\x01A\x02\x01\
A\x06\x01B\x04\x01@\x01\x0cbar-pressurev\0v\x04\0\x0econvert-to-psi\x01\0\x01@\x01\
\x0cpsi-pressurev\0v\x04\0\x0econvert-to-bar\x01\x01\x03\0%data:transformer/mess\
age-transformers\x05\0\x01B\x03\x01@\x01\x03valv\0\x7f\x04\0\x0cvalidate-bar\x01\
\0\x04\0\x0cvalidate-psi\x01\0\x03\0\x1ddata:validator/unit-validator\x05\x01\x01\
B\x02\x01@\x01\x06sources\0v\x04\0\x03run\x01\0\x04\0!data:transformer/component\
-runner\x05\x02\x04\0\x1cdata:transformer/transformer\x04\0\x0b\x11\x01\0\x0btra\
nsformer\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.2\
27.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
